### ISSUE TITLE
App Flowy show a black screen at start

### ISSUE THREAD

**Issue by yodatak** [flathub/io.appflowy.AppFlowy#12]
flatpak run io.appflowy.AppFlowy 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_stream_port (package:appflowy_backend/ffi.dart)
#5      set_stream_port (package:appflowy_backend/ffi.dart)
#6      FlowySDK.init (package:appflowy_backend/appflowy_backend.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:24)
<asynchronous suspension>
#8      AppLauncher.launch (package:app_flowy/startup/startup.dart:124)
<asynchronous suspension>
#9      FlowyRunner.run (package:app_flowy/startup/startup.dart:64)
<asynchronous suspension>
#10     main (package:app_flowy/main.dart:25)
<asynchronous suspension>
```

It seem to be a libssl incompatibily we shoud add it to the flatpak if needed

**Comment by tommy4st** [comment]
(Just for the sake of completeness, in English:)

```
$ flatpak run io.appflowy.AppFlowy

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_stream_port (package:appflowy_backend/ffi.dart)
#5      set_stream_port (package:appflowy_backend/ffi.dart)
#6      FlowySDK.init (package:appflowy_backend/appflowy_backend.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:24)
<asynchronous suspension>
#8      AppLauncher.launch (package:app_flowy/startup/startup.dart:124)
<asynchronous suspension>
#9      FlowyRunner.run (package:app_flowy/startup/startup.dart:64)
<asynchronous suspension>
#10     main (package:app_flowy/main.dart:25)
<asynchronous suspension>
```
